export const GLOSSARY: Record<string, string> = {
  SELECT: "Picks which columns show up in the result. It runs last, even though we write it first.",
  FROM: "Names the table to read rows from — the starting point of every query.",
  WHERE: "Keeps only the rows that match a condition. Checked one row at a time, before grouping or sorting.",
  "GROUP BY": "Collapses rows that share the same value in a column into a single group, so you can summarize each group.",
  HAVING: "Same idea as WHERE, but it filters whole groups after GROUP BY — WHERE can't do this because groups don't exist yet when WHERE runs.",
  "ORDER BY": "Sorts the rows that are left, either smallest-to-largest (ASC) or largest-to-smallest (DESC).",
  LIMIT: "Keeps only the first N rows after sorting, and throws the rest away.",
  "COUNT(*)": "Counts how many rows are in each group.",
  SUM: "Adds up a column's values within each group.",
  AVG: "Averages a column's values within each group.",
  likes_count: "How many likes that post has.",
  views_count: "How many times that post was viewed.",
  format: "Whether the post is an image or a video.",
  username: "Who posted it.",
  DESC: "Descending — biggest value first.",
  ASC: "Ascending — smallest value first.",
  index: "A shortcut list MySQL can build on a column — like a book's index — so it can jump straight to matching rows instead of opening every single one.",
  JOIN: "Combines rows from two separate tables into one wider row, matched on a shared column.",
  "INNER JOIN": "Keeps only the rows that have a match in both tables — anything unmatched, on either side, is dropped entirely.",
  "LEFT JOIN": "Keeps every row from the first (left) table no matter what — if there's no match on the right, those columns just come back empty.",
  ON: "The condition MySQL uses to decide which row from the first table belongs with which row from the second.",
  UNION: "Stacks the results of two SELECTs into one list and removes exact duplicate rows.",
  INTERSECT: "Keeps only the rows that show up in both SELECTs' results.",
  EXCEPT: "Keeps rows from the first SELECT that do NOT also appear in the second SELECT's results.",
  subquery: "A query nested inside another query. MySQL runs the inner one first and feeds its result into the outer query — as if it were typed there directly.",
  "scalar subquery": "A subquery that returns exactly one value — one row, one column — so it can stand in anywhere a single number is expected, like next to > or =.",
};

export type GlossaryTerm = keyof typeof GLOSSARY;
